"""add column = user_surname

Revision ID: 1319f8e7c1e4
Revises: 44b723fffaf6
Create Date: 2023-12-05 16:23:51.251596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1319f8e7c1e4'
down_revision = '44b723fffaf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_surname', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_user_surname'), ['user_surname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_user_surname'), type_='unique')
        batch_op.drop_column('user_surname')

    # ### end Alembic commands ###
