"""empty message

Revision ID: 44b723fffaf6
Revises: 609bad80cc9f
Create Date: 2023-12-05 16:22:31.502038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b723fffaf6'
down_revision = '609bad80cc9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('user_surname', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_users'),
    sa.UniqueConstraint('user_name', name='uq_users_user_name'),
    sa.UniqueConstraint('user_surname', name='uq_users_user_surname')
    )
    # ### end Alembic commands ###
