"""users, add fild = user_surname

Revision ID: 466b7084a030
Revises: 
Create Date: 2023-12-03 08:36:44.810480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466b7084a030'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_surname', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_users_user_surname'), ['user_surname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_user_surname'), type_='unique')
        batch_op.drop_column('user_surname')

    # ### end Alembic commands ###
