"""Расширили модель пользователя

Revision ID: 36ee656fe0f6
Revises: 
Create Date: 2023-12-02 20:36:23.362767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ee656fe0f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_surname', sa.String(length=80), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_all_users_user_name'), ['user_name'])
        batch_op.create_unique_constraint(batch_op.f('uq_all_users_user_surname'), ['user_surname'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_posts_text'), ['text'])
        batch_op.create_unique_constraint(batch_op.f('uq_posts_title'), ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_posts_title'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_posts_text'), type_='unique')

    with op.batch_alter_table('all_users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_all_users_user_surname'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_all_users_user_name'), type_='unique')
        batch_op.drop_column('user_surname')

    # ### end Alembic commands ###
