# Generated by Django 5.0.3 on 2024-03-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('u', 'User'), ('m', 'Moderator'), ('a', 'Administrator')], default='', max_length=155, verbose_name='Роль пользователя'),
        ),
    ]
