"""correction my errors

Revision ID: 5afb8148067e
Revises: 
Create Date: 2023-12-09 19:55:48.198055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5afb8148067e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=False))
        batch_op.drop_column('adress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adress', sa.TEXT(), nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
